name: crazy-train

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    - name: Install dependencies
      run: |
        cd app/crazy_train
        bundle install
    - name: Lint with Rubocop
      run: |
        cd app
        rubocop -l
#    - name: Run migrations for integration tests
#      run: |
#        cd app
#        poetry run alembic -x db=test upgrade head
    - name: Test with minitest
      run: |
        cd app/crazy_train
        ./bin/rails test -v
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v2
      with:
        files: ./app/crazy_train/coverage/lcov/crazy_train.lcov
        fail_ci_if_error: true
        verbose: true
