name: crazy-train

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    - name: Install dependencies
      run: |
        cd app/crazy_train
        bundle install
#    - name: Lint with flake8
#      run: |
#        cd app
#        poetry run flake8 ./py_lyfe --max-complexity 10 --exclude ./py_lyfe/alembic
#    - name: Run migrations for integration tests
#      run: |
#        cd app
#        poetry run alembic -x db=test upgrade head
    - name: Test with minitest
      run: |
        cd app/crazy_train
        CI=true ./bin/rails test -v
    - name: Upload coverage to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./app/crazy_train/coverage/lcov/crazy_train.lcov
        base-path: app/crazy_train
      env:
        NODE_COVERALLS_DEBUG: 1
